services:
  flet:
    extends:
      file: docker-compose-python_template.yml
      service: python
    build:
      context: ./frontend/flet
    container_name: flet
    restart: always
    environment:
      - FLET_FORCE_WEB_SERVER=true
      - FLET_SERVER_PORT=${PORT_FLET}
      - FLET_APP_LIFETIME_MINUTES=10
      - DOMAIN=${DOMAIN}
      - SUBDOMAIN_API=${SUBDOMAIN_API}
      - SUBDOMAIN_FLET=${SUBDOMAIN_FLET}
    # ports:
    #  - "${PORT_FLET}:${PORT_FLET}"
    volumes:
      - ./frontend/flet/log:/usr/src/app/log
      - ./frontend/flet/src:/usr/src/app/src:volume-nocopy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flet-app.rule=Host(`${SUBDOMAIN_FLET}${DOMAIN}`)"
      - "traefik.http.routers.flet-app.entrypoints=websecure"
      - "traefik.http.services.flet-app.loadbalancer.server.port=${PORT_FLET}"
      - "traefik.http.routers.flet-app.tls.certresolver=letsencrypt"
    depends_on:
      - db
      - redis