services:
  api:
    extends:
      file: docker-compose-python_template.yml
      service: python
    build:
      context: backend/api-fastapi
    container_name: api-fastapi
    # ports:
    #  - "${PORT_API}:${PORT_API}"
    volumes:
      - ./backend/api-fastapi/log:/usr/src/app/log
      - ./backend/api-fastapi/src:/usr/src/app/src:volume-nocopy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-fastapi-secure.rule=Host(`${SUBDOMAIN_API}${DOMAIN}`)"
      - "traefik.http.routers.api-fastapi-secure.entrypoints=websecure"
      - "traefik.http.services.api-fastapi-secure.loadbalancer.server.port=${PORT_API}"
      - "traefik.http.routers.api-fastapi-secure.tls.certresolver=letsencrypt"
    command:
      - /bin/sh
      - -c
      - |
        cd /usr/src/app/src
        uvicorn main:api --reload --workers 1 --host "0.0.0.0" --port ${PORT_API} --proxy-headers
    depends_on:
      - db
      # db:
      #  condition: service_healthy