# https://hub.docker.com/r/hasura/graphql-engine

services:
    db:
      image: mariadb:latest
      container_name: mariadb
      restart: always

      stdin_open: true # docker run -i
      tty: true        # docker run -t
      volumes:
        - ./.mariadb/certs:/etc/mysql/certs
        - ./.mariadb/conf.d/secure.cnf:/etc/mysql/conf.d/secure.cnf
        - ./.mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        # uncomment if docker volume is necessary
        # - ${DB_VOLUME_NAME}:/var/lib/mysql
        - ./.mariadb/${DB_VOLUME_NAME}:/var/lib/mysql
        - /etc/localtime:/etc/localtime
      environment:
        MARIADB_ROOT_PASSWORD: example
      # uncomment to make it visible on the host to get ssh access
      ports:
        - "${PORT_DB}:3306"
      healthcheck:
        test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
        interval: 10s
        timeout: 30s
        start_period: 60s
        start_interval: 10s
        retries: 3

      # expose made it visible on the backnet but not on the host
      expose:
        - "${PORT_DB}"
        - "33060"
      networks:
        - backnet

    phpmyadmin:
      image: phpmyadmin
      container_name: phpmyadmin
      restart: always
      # ports:
      #  - ${PORT_PHPMYADMIN}:80
      environment:
        # uncomment if host should be selected on page
        # - PMA_ARBITRARY=1
        - PMA_HOST=db
        - PMA_ABSOLUTE_URI=https://${SUBDOMAIN_PHPMYADMIN}${DOMAIN}
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.phpmyadmin.rule=Host(`${SUBDOMAIN_PHPMYADMIN}${DOMAIN}`)"
        - "traefik.http.routers.phpmyadmin.entrypoints=websecure"
        - "traefik.http.routers.phpmyadmin.tls.certresolver=letsencrypt"
        - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
        - "traefik.http.routers.phpmyadmin.tls=true"
      depends_on:
        - db
        #db:
        #  condition: service_healthy
      networks:
        - backnet

    adminer:
      image: adminer
      container_name: adminer
      restart: always
      # ports:
      #  - "${PORT_ADMINER}:8080"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.adminer.rule=Host(`${SUBDOMAIN_ADMINER}${DOMAIN}`)"
        - "traefik.http.routers.adminer.entrypoints=websecure"
        - "traefik.http.routers.adminer.tls.certresolver=letsencrypt"
        - "traefik.http.services.adminer.loadbalancer.server.port=8080"
        - "traefik.http.routers.adminer.tls=true"
      depends_on:
        - db
        # db:
        #  condition: service_healthy
      networks:
        - backnet

    # Max Scale - it is running but has some issues
    # username is admin and the password is mariadb
    maxscale:
      image: mariadb/maxscale:latest
      container_name: maxscale
      # volumes:
      #  - ./.mariadb/maxscale/maxscale.cnf:/etc/maxscale.cnf.d/maxscale.cnf
      ports:
        - 0.0.0.0:4006:4006 # readwrite port
        - 0.0.0.0:4008:4008 # readonly port
        - 0.0.0.0:8989:8989 # REST API port
      links:
        # to fix - here could be a potential bug
        - db:database
      depends_on:
        - db
        #db:
        #  condition: service_healthy
      networks:
        - backnet

# volumes:
#  db_data:
#      name: ${DB_VOLUME_NAME}