services:
  api-fastapi-sqlmodel:
    extends:
      file: docker-compose-python_template.yml
      service: python
    build:
      context: backend/api-fastapi-sqlmodel
    container_name: api-fastapi-sqlmodel
    restart: always
    environment:
      - DOMAIN=${DOMAIN}
      - SUBDOMAIN_API=${SUBDOMAIN_API}
      - SUBDOMAIN_JURY=${SUBDOMAIN_JURY}
    # ports:
    #  - "${PORT_API}:${PORT_API}"
    volumes:
      - ./backend/api-fastapi-sqlmodel/log:/usr/src/app/log
      - ./backend/api-fastapi-sqlmodel/src:/usr/src/app/src:volume-nocopy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-fastapi-sqlmodel.rule=Host(`${SUBDOMAIN_API}${DOMAIN}`)"
      - "traefik.http.routers.api-fastapi-sqlmodel.entrypoints=websecure"
      - "traefik.http.services.api-fastapi-sqlmodel.loadbalancer.server.port=${PORT_API}"
      - "traefik.http.routers.api-fastapi-sqlmodel.tls.certresolver=letsencrypt"
    command:
      - /bin/sh
      - -c
      - |
        cd /usr/src/app/src
        uvicorn main:api --reload --workers 1 --host "0.0.0.0" --port ${PORT_API} --proxy-headers
    depends_on:
      - db
      - redis